# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - sb-img-insight

on:
    workflow_dispatch:
      inputs:
        pack-name:
          description: 'package name'
          type: choice
          options:
            - 'img-insight-extn'
          default: 'img-insight-extn'
          required: true
        app-name:
          description: 'app name'
          type: choice
          options:
            - 'sb-img-insight'
          default: 'sb-img-insight'
          required: true
            
env:
    AZURE_WEBAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root
    NODE_VERSION: '18.x'  # set this to the node version to use
permissions:
  contents: read
  id-token: write

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './${{inputs.pack-name}}/package-lock.json'
  
      - name: npm install, build, and test
        run: |
          cd ./${{inputs.pack-name}}
          npm install
          npm run build --if-present
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./${{inputs.pack-name}}

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      permissions:
        id-token: write #This is required for requesting the JWT

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: node-app
      
        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FD4615B911FD41C2B4B2C6D0B4C61FD2 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_23373563207F40DF94B076E484A54F89 }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7AC760683A57450991F6038EDE40E70B }}

        - name: 'Deploy to Azure Web App'
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v3
          with:
            app-name: 'sb-img-insight'
            slot-name: 'Production'
            package: .
          
